### DISCUSSION TITLE
[Docker] npm/yarn uws package download error from github

### DISCUSSION THREAD

**Discussion by vimalmistry** [uNetworking/uWebSockets.js#608] [Q&A]
I am trying to make a docker container build using my existing project which is uwebsocket.js with mongo and Redis. 

here is my Dockerfile

```
FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
# COPY package-json.lock ./
RUN npm install
# Copy in the source
COPY . .

RUN npm run build

# Expose Port
EXPOSE 9001

# Run the app
CMD ["node", "build/index.js"]

```

When I use npm its give me
```
 > [5/7] RUN npm install:                                                                               
#9 10.78 npm WARN tarball tarball data for uWebSockets.js@git+ssh://git@github.com/uNetworking/uWebSockets.js.git (null) seems to be corrupted. Trying again.                                                   
#9 11.14 npm WARN tarball tarball data for uWebSockets.js@git+ssh://git@github.com/uNetworking/uWebSockets.js.git (null) seems to be corrupted. Trying again.   
```

And Using yarn.

```
#11 4.452 Arguments: ls-remote --tags --heads ssh://git@github.com/uNetworking/uWebSockets.js.git
#11 4.452 Directory: /usr/src/app
#11 4.452 Output:
#11 4.452 Host key verification failed.
#11 4.452 fatal: Could not read from remote repository.
```
This is my first time using docker. I don't know much about it.

Also, I have a question. how to implement worker threads in docker. If I spin up multiple containers using docker-compose.yml. Then I think the node worker thread will not works.

If anyone created successfully docker-compose and dockerfile can guide me.

Here is docker-compose.yml. It is working fine with the express and koa apps.

```
version: "3.9"
services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "9001:9001"
    env_file: ./.env
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
      - redis
    # networks:
    #   - app-network
  mongo:
    image: mongo
    volumes:
      - ./data-volume:/data/db
    ports:
      - "27017:27017"
    # networks:
    #   - app-network
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge

# volumes:
#   data-volume:
#   node_modules:
#   web-root:
#     driver: local

```
